#define IPv4 257
#define IPv6 258
#define HOSTADDR 259
#define WORD 260
#define INTEGER 261
#define SYSLOG_BANNER_PID 262
#define SOCKLOG_BANNER_PID 263
#define SYSLOG_BANNER 264
#define TIMESTAMP_SYSLOG 265
#define TIMESTAMP_ISO8601 266
#define TIMESTAMP_TAI64 267
#define AT_TIMESTAMP_TAI64 268
#define METALOG_BANNER 269
#define SOCKLOG_BANNER 270
#define HTTP_REQUEST 271
#define HTTP_VERSION 272
#define HTTP_REDIRECT 273
#define HTTP_AUTHFAIL 274
#define HTTP_CLIERROR 275
#define HTTP_BOTSEARCH_WEBMAIL 276
#define HTTP_BOTSEARCH_PHPMYADMIN 277
#define HTTP_BOTSEARCH_WORDPRESS 278
#define HTTP_BOTSEARCH 279
#define SSH_INVALUSERPREF 280
#define SSH_NOTALLOWEDPREF 281
#define SSH_NOTALLOWEDSUFF 282
#define SSH_LOGINERR_PREF 283
#define SSH_LOGINERR_PAM 284
#define SSH_VIA 285
#define SSH_MAXAUTH 286
#define SSH_ADDR_SUFF 287
#define SSH_NOIDENTIFSTR 288
#define SSH_BADPROTOCOLIDENTIF 289
#define SSH_BADPROTOCOLIDENTIF_SUFF 290
#define SSH_BADKEX_PREF 291
#define SSH_BADKEX_SUFF 292
#define SSH_DISCONNECT_PREF 293
#define SSH_PREAUTH_SUFF 294
#define SSHGUARD_ATTACK_PREF 295
#define SSHGUARD_ATTACK_SUFF 296
#define SSHGUARD_BLOCK_PREF 297
#define SSHGUARD_BLOCK_SUFF 298
#define DOVECOT_IMAP_LOGINERR_PREF 299
#define DOVECOT_IMAP_LOGINERR_SUFF 300
#define UWIMAP_LOGINERR 301
#define CYRUSIMAP_SASL_LOGINERR_PREF 302
#define CYRUSIMAP_SASL_LOGINERR_SUFF 303
#define CUCIPOP_AUTHFAIL 304
#define EXIM_ESMTP_AUTHFAIL_PREF 305
#define EXIM_ESMTP_AUTHFAIL_SUFF 306
#define SENDMAIL_RELAYDENIED_PREF 307
#define SENDMAIL_RELAYDENIED_SUFF 308
#define SENDMAIL_AUTHFAILURE_PREF 309
#define SENDMAIL_AUTHFAILURE_SUFF 310
#define POSTFIX_NO_AUTH_PREF 311
#define POSTFIX_SASL_LOGINERR_PREF 312
#define POSTFIX_SASL_LOGINERR_SUFF 313
#define FREEBSDFTPD_LOGINERR_PREF 314
#define FREEBSDFTPD_LOGINERR_SUFF 315
#define PROFTPD_LOGINERR_PREF 316
#define PROFTPD_LOGINERR_SUFF 317
#define PUREFTPD_LOGINERR_PREF 318
#define PUREFTPD_LOGINERR_SUFF 319
#define VSFTPD_LOGINERR_PREF 320
#define VSFTPD_LOGINERR_SUFF 321
#define COCKPIT_AUTHFAIL_PREF 322
#define COCKPIT_AUTHFAIL_SUFF 323
#define CLF_REQUEST_PREF 324
#define CLF_UNAUTHOIRIZED_PREF 325
#define CLF_UNAUTHOIRIZED_SUFF 326
#define CLFWEBPROBES_BOTSEARCH_SUFF 327
#define CLF_WORDPRESS_SUFF 328
#ifdef YYSTYPE
#undef  YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
#endif
#ifndef YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
typedef union {
    char *str;
    int num;
} YYSTYPE;
#endif /* !YYSTYPE_IS_DECLARED */
extern YYSTYPE yylval;
